name: Build docker images

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set CONNECT_BASE_VERSION env variable
        run: echo "CONNECT_BASE_VERSION=$(cat ./CONNECT_BASE_VERSION)" >> $GITHUB_ENV

      - name: Build and push connect-base
        id: docker_build_base
        uses: docker/build-push-action@v2
        with:
          context: ./connect-base
          file: ./connect-base/Dockerfile
          push: true
          tags: |
            d0rka/connect-base:latest
            d0rka/connect-base:${{ env.CONNECT_BASE_VERSION }}

      - name: Build and push spooldir-connect-base
        id: docker_build_spooldir
        uses: docker/build-push-action@v2
        with:
          build-args: CONNECT_BASE_VERSION=${{ env.CONNECT_BASE_VERSION }}
          context: ./spooldir-connect-base
          file: ./spooldir-connect-base/Dockerfile
          push: true
          tags: |
            d0rka/spooldir-connect-base:latest
            d0rka/spooldir-connect-base:${{ env.CONNECT_BASE_VERSION }}

      - name: Build and push jdbc-connect-base
        id: docker_build_jdbc
        uses: docker/build-push-action@v2
        with:
          build-args: CONNECT_BASE_VERSION=${{ env.CONNECT_BASE_VERSION }}
          context: ./jdbc-connect-base
          file: ./jdbc-connect-base/Dockerfile
          push: true
          tags: |
            d0rka/jdbc-connect-base:latest
            d0rka/jdbc-connect-base:${{ env.CONNECT_BASE_VERSION }}

      - name: Build and push debezium-postgres-connect-base
        id: docker_build_debezium
        uses: docker/build-push-action@v2
        with:
          build-args: CONNECT_BASE_VERSION=${{ env.CONNECT_BASE_VERSION }}
          context: ./debezium-postgres-connect-base
          file: ./debezium-postgres-connect-base/Dockerfile
          push: true
          tags: |
            d0rka/debezium-postgres-connect-base:latest
            d0rka/debezium-postgres-connect-base:${{ env.CONNECT_BASE_VERSION }}

      - name: Build and push jdbc-debezium-postgres-connect-base
        id: docker_build_jdbc_debezium
        uses: docker/build-push-action@v2
        with:
          build-args: CONNECT_BASE_VERSION=${{ env.CONNECT_BASE_VERSION }}
          context: ./jdbc-debezium-postgres-connect-base
          file: ./jdbc-debezium-postgres-connect-base/Dockerfile
          push: true
          tags: |
            d0rka/jdbc-debezium-postgres-connect-base:latest
            d0rka/jdbc-debezium-postgres-connect-base:${{ env.CONNECT_BASE_VERSION }}